### ISSUE TITLE
LeetPlug not showing when a problem is opened from 'Similar Questions'

### ISSUE THREAD

**Issue by vedangwartikar** [LorenzoBe/LeetPlug#1]
LeetPlug works everytime a problem is opened from the 'Problemset' or the 'Tag' section. But fails to load when a problem is accesed through the 'Similar Questions' from the 'Description' in the left panel.

**Comment by LorenzoBe** [comment]
Thanks, I never tested this path :D It's easily reproducible but difficult to solve: I just realised that when you use the Similar Questions it doesn't reload the page, and I have everything connected to the onLoad event.
So one workaround is to click on the ling and then reload the page. But clearly I instead need to find a smarter way to have it really working!
Thanks for pointing to it

**Comment by vedangwartikar** [comment]
Maybe you could call `location.reload();` once a user accesses a problem through the Similar Questions. I haven't worked a lot on Web dev so not sure if it'll work.

**Comment by LorenzoBe** [comment]
Dear Vedang, thanks for your suggestion. I preferred to avoid to reload every time the page. There were also many other paths to reach the problems, and I tried to cover all of them. Version 1.0.8 of the extension is under review and should be published soon. Meantime if you need it urgently you could beta-test it cloning the repo and loading the extension directly from local code :D I would be less scared, since I changed a lot I hope I didn't screw everything...

**Comment by LorenzoBe** [comment]
Extension has been published in version 1.0.9. Hopefully all paths to problems has been covered... :)

**Comment by vedangwartikar** [comment]
Great work! Gave it a 5 star rating on Chrome Web Store. Hope to see more exciting features
