### ISSUE TITLE
Reset Timer button

### ISSUE THREAD

**Issue by vteja11** [LorenzoBe/LeetPlug#10]
It will be good to add a small reset button where the timer shows

**Comment by gupta-anmol** [comment]
You can just refresh the page to reset the timer. Personally, I feel the status quo is fine as not having a dedicated reset button discourages people from faking their time, and it'd probably be better to avoid this since the app may have features such as performance comparison with other users in the future.

**Comment by LorenzoBe** [comment]
Thank you @vteja11 for the suggestion and @gupta-anmol for the answer. I share the same opinion.
There are other LeetCode extensions that allow you to have a better timer, with probably pause and reset. But this is not the purpose of LeetPlug.
Here we would like to keep the real effort done to solve a problem and keep track of all the failures. Obviously sometimes you simply need to answer the phone or do some urgent task, and the result is skewd. But these should be exceptions to the standard rule.
People can fake in any case, reloading the page and copy/pasting the solution, so I think that a real user comparison will not be really meaningful (even if it was my initial goal).
Probably I will soon or later introduce some statistics about the most solved problems, with the average time required to solve it.
